name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: setup
        run: npm i -g @vscode/vsce

      - name: build
        run: vsce package
     
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vscode-extension
          path: "*.vsix" # Adjust the path if the file has a different name or location

      
